# GET Resources - will also update the current
GET http://localhost:3000/api/army/card
Content-Type: application/json

{}

### expexted return:

# NAME rest the recources
GET http://localhost:3000/api//army/attack
Content-Type: application/json

### expexted return: player
