
# gereate building with sending type and p
GET http://localhost:3000/api/buildings/upgrade?type=0&p=2&id={{id}}
Content-Type: application/json

{}

### expexted return: player

# upgrade level (only p), building has to exist
GET http://localhost:3000/api/buildings/upgrade?p=2&id={{id}}
Content-Type: application/json

{}

### expexted return: player

# delete item
GET http://localhost:3000/api/buildings/upgrade?p=2&id={{id}}
Content-Type: application/json

{}

### expexted return: player


# get current buildings
GET http://localhost:3000/api/buildings?id={{id}}
Content-Type: application/json

{}

### expexted return: buildings

