GET http://localhost:3000/api/player
Content-Type: application/json

{}

### expected return: Error

PUT http://localhost:3000/api/player
Content-Type: application/json

{}

### expexted return: player


GET http://localhost:3000/api/player?id=399011e1-408f-46e5-bfc1-2068b43f2c0c
Content-Type: application/json

{}

### expexted return: player
DELETE http://localhost:3000/api/player?id=399011e1-408f-46e5-bfc1-2068b43f2c0c
Content-Type: application/json

{}

### expexted return: {}
